return {
	-- {
	-- 	"luukvbaal/statuscol.nvim",
	-- 	event = "BufReadPre",
	-- 	opts = function()
	-- 		local builtin = require("statuscol.builtin")
	-- 		return {
	-- 			setopt = true,
	-- 			relculright = false,
	-- 			segments = {
	-- 				{
	-- 					text = { builtin.foldfunc },
	-- 					click = "v:lua.ScFa",
	-- 				},
	-- 				{
	-- 					text = { " %s" },
	-- 					click = "v:lua.ScSa",
	-- 				},
	-- 				{
	-- 					text = { builtin.lnumfunc, " " },
	-- 					condition = { true, builtin.not_empty },
	-- 					click = "v:lua.ScLa",
	-- 				},
	-- 			},
	-- 		}
	-- 	end,
	-- },
}
