{
  config = ''
              -- WARN: This file has been generated by home manager and pulled from the dotfiles repo
      return {
    	{
    		"catppuccin/nvim",
    		name = "catppuccin",
    		priority = 1000,
    		opts = {
    			flavour = "mocha",
    			transparent_background = true,
    			term_colors = true,
    			styles = {
    				keywords = { "italic" },
    				booleans = { "italic" },
    				loops = { "bold" },
    				functions = { "italic", "bold" },
    			},
    			color_overrides = {
    				mocha = {
    					rosewater = "#42be65",
    					flamingo = "#33b1ff",
    					pink = "#3ddbd9",
    					mauve = "#78a9ff",
    					red = "#EE5396",
    					maroon = "#be95ff",
    					peach = "#08bdba",
    					yellow = "#82cfff",
    					green = "#be95ff",
    					teal = "#08bdba",
    					sky = "#89dceb",
    					sapphire = "#74c7ec",
    					blue = "#ff7eb6",
    					lavender = "#c5c9d9",
    					text = "#cdd6f4",
    					subtext1 = "#bac2de",
    					subtext0 = "#a6adc8",
    					overlay2 = "#9399b2",
    					overlay1 = "#7f849c",
    					overlay0 = "#6c7086",
    					surface2 = "#585b70",
    					surface1 = "#45475a",
    					surface0 = "#313244",
    					base = "#0d0d0d",
    					mantle = "#1C1C21",
    					crust = "#151517",
    				},
    			},
    			highlight_overrides = {
    				mocha = function(mocha)
    					return {
    						-- UI --
    						NormalFloat = { bg = mocha.crust },
    						FloatBorder = { bg = mocha.crust, fg = mocha.crust },
    						LineNrAbove = { fg = mocha.surface1 },
    						LineNrBelow = { fg = mocha.surface1 },
    						LineNr = { fg = mocha.text },
    						TermCursor = { link = "Cursor" },

    						-- SYNTAX --
    						Comment = { fg = mocha.overlay0 },
    						Directory = { fg = mocha.peach, bold = true },

                            -- HEIRLINE --
                            HeirlineNormal = { fg = "#715688", bg = "#715688" },
                            HeirlineVisual = { fg = "#40739a", bg = "#40739a" },
                            HeirlineInsert = { fg = "#729b79", bg = "#729b79" },
                            HeirlineCommand = { fg = "#b99bb5", bg = "#b99bb5" },
                            HeirlineTerminal = { fg = "#729b79", bg = "#729b79" },
                            HeirlineReplace = { fg = "#a78a58", bg = "#a78a58" },
                            HeirlineInactive = { fg = "#777777", bg = "#777777" },
                            StatusNormal = { fg = "#715688", bg = "#715688" },
                            StatusVisual = { fg = "#40739a", bg = "#40739a" },
                            StatusInsert = { fg = "#729b79", bg = "#729b79" },
                            StatusCommand = { fg = "#b99bb5", bg = "#b99bb5" },
                            StatusTerminal = { fg = "#729b79", bg = "#729b79" },
                            StatusReplace = { fg = "#a78a58", bg = "#a78a58" },
                            StatusInactive = { fg = "#777777", bg = "#777777" },


    						-- GITSIGNS --
    						GitSignsAdd = { fg = mocha.pink },
    						GitSignsChange = { fg = mocha.green },
    						GitSignsDelete = { fg = mocha.blue },

                            -- FLOG --
    					    flogBranch0 = { fg = colors.rosewater },
    					    flogBranch1 = { fg = colors.rosewater },
    					    flobBranch2 = { fg = colors.lavender },
    					    flogBranch3 = { fg = colors.peach },
    					    flogBranch4 = { fg = colors.red },
    					    flogBranch5 = { fg = colors.yellow },
    					    flogBranch6 = { fg = colors.teal },
    					    flogBranch7 = { fg = colors.pink },
    					    flogBranch8 = { fg = colors.sky },
    					    flogDate = { fg = colors.blue, italic = true },

    						-- DIFF --
    						diffAdded = { fg = mocha.pink },
    						diffRemoved = { fg = mocha.blue },
    						diffChanged = { fg = mocha.green },
    						DiffAdd = { bg = "#03302F" },
    						DiffDelete = { bg = "#300316" },
    						DiffChange = { bg = "#2b2534" },
    						DiffviewHash = { fg = mocha.mauve },
    						DiffviewFilePanelTitle = { fg = mocha.blue },
    						DiffviewFilePanelSelected = { fg = mocha.text, bold = true },
    						DiffviewFilePanelFileName = { fg = mocha.subtext0 },

    						-- DIAGNOSTICS --
    						DiagnosticSignError = { fg = mocha.red },
    						DiagnosticVirtualTextError = { fg = mocha.red, bg = "#31272a", bold = true, italic = true },
    						DiagnosticSignWarn = { fg = "#f9e2af" },
    						DiagnosticUnderlineWarn = { sp = "#f9e2af" },
    						DiagnosticVirtualTextWarn = { fg = "#f9e2af", bg = "#312f27", bold = true, italic = true },
    						DiagnosticWarn = { fg = "#f9e2af" },
    						DiagnosticSignInfo = { fg = mocha.pink },
    						DiagnosticVirtualTextInfo = { fg = mocha.pink, bg = "#252e2e", bold = true, italic = true },
    						DiagnosticInfo = { fg = mocha.pink },
    						DiagnosticSignHint = { fg = mocha.green },
    						DiagnosticVirtualTextHint = { fg = mocha.green, bg = "#2b2731", bold = true, italic = true },
    						DiagnosticHint = { fg = mocha.green },
    						DiagnosticSignOk = { fg = mocha.rosewater },
    						DiagnosticUnderlineOk = { sp = mocha.rosewater },
    						DiagnosticVirtualTextOk = { fg = mocha.rosewater, bg = "#283127", bold = true, italic = true },
    						DiagnosticUnnecessary = { fg = "#777777", italic = true },

    						-- CMP --
    						CmpItemKind = { bg = mocha.blue, fg = mocha.base },
    						CmpItemKindEnum = { bg = mocha.green, fg = mocha.base },
    						CmpItemKindFile = { bg = mocha.green, fg = mocha.base },
    						CmpItemKindText = { bg = mocha.sky, fg = mocha.base },
    						CmpItemKindUnit = { bg = mocha.green, fg = mocha.base },
    						CmpItemKindClass = { bg = mocha.yellow, fg = mocha.base },
    						CmpItemKindColor = { bg = mocha.red, fg = mocha.base },
    						CmpItemKindEvent = { bg = mocha.blue, fg = mocha.base },
    						CmpItemKindField = { bg = mocha.green, fg = mocha.base },
    						CmpItemKindValue = { bg = mocha.teal, fg = mocha.base },
    						CmpItemKindFolder = { bg = mocha.rosewater, fg = mocha.base },
    						CmpItemKindMethod = { bg = mocha.blue, fg = mocha.base },
    						CmpItemKindModule = { bg = mocha.flamingo, fg = mocha.base },
    						CmpItemKindStruct = { bg = mocha.blue, fg = mocha.base },
    						CmpItemKindCopilot = { bg = mocha.teal, fg = mocha.base },
    						CmpItemKindDefault = { bg = mocha.pink, fg = mocha.base },
    						CmpItemKindKeyword = { bg = mocha.mauve, fg = mocha.base },
    						CmpItemKindSnippet = { bg = mocha.rosewater, fg = mocha.base },
    						CmpItemKindConstant = { bg = mocha.teal, fg = mocha.base },
    						CmpItemKindFunction = { bg = mocha.flamingo, fg = mocha.base },
    						CmpItemKindFunctionDefault = { bg = mocha.flamingo, fg = mocha.base },
    						CmpItemKindOperator = { bg = mocha.blue, fg = mocha.base },
    						CmpItemKindProperty = { bg = mocha.pink, fg = mocha.base },
    						CmpItemKindVariable = { bg = mocha.green, fg = mocha.base },
    						CmpItemKindInterface = { bg = mocha.yellow, fg = mocha.base },
    						CmpItemKindReference = { bg = mocha.red, fg = mocha.base },
    						CmpItemKindEnumMember = { bg = mocha.red, fg = mocha.base },
    						CmpItemKindConstructor = { bg = mocha.blue, fg = mocha.base },
    						CmpItemKindTypeParameter = { bg = mocha.blue, fg = mocha.base },

    						-- UFO --
    						UfoFoldedEllipsis = { bg = "NONE", fg = mocha.overlay0 },

    						-- MASON --
    						MasonHeader = { bg = mocha.rosewater, fg = mocha.base },

    						-- NEOTEST --
    						NeotestPassed = { fg = mocha.rosewater },
    						NeotestAdapterName = { fg = mocha.green, bold = true },
    						NeotestDir = { fg = mocha.sapphire, underline = true },
    						NeotestFile = { fg = mocha.text, bold = true, italic = true },
    						NeotestTest = { fg = mocha.overlay1 },
    						NeotestFailed = { fg = mocha.red },
    						NeotestRunning = { fg = mocha.teal },
    						NeotestSkipped = { fg = mocha.flamingo },

    						-- DAPUI --
    						DapUIPlayPause = { fg = "#8CFF48" },
    						DapUIStop = { fg = "#DF025A" },
    						DapUIStepOver = { fg = "#00F5F7" },
    						DapUIStepInto = { fg = "#00F5F7" },
    						DapUIStepOut = { fg = "#00F5F7" },
    						DapUIStepBack = { fg = "#00F5F7" },

    						-- WHICHKEY --
    						WhichKeyDesc = { fg = mocha.text },
    						WhichKeyGroup = { fg = mocha.blue, italic = true },
    						WhichKey = { fg = mocha.teal },

    						-- SNACKS --
    						SnacksIndent = { fg = mocha.mantle },
    						SnacksIndentChunk = { fg = mocha.yellow },
    					}
    				end,
    			},
    		},
    		config = function(_, opts)
    			require("catppuccin").setup(opts)
    			vim.cmd.colorscheme("catppuccin")
    		end,
    	},
    }
  '';
}
