-- require('notify').setup({
--   stages = "slide",
--   timeout = 3000,
--   background_colour = "#000000",
--   icons = {
--     ERROR = " ",
--     WARN = " ",
--     INFO = " ",
--     DEBUG = " ",
--     TRACE = "✎ ",
--   }
-- })
